// Image CDN URL for Restaurant card
export const IMG_CDN_URL =
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/";

// Image CDN URL for Restaurant Menu
export const ITEM_IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/";

// Swiggy API to get Restaurant data with foodfire server
export const swiggy_api_URL =
  "https://www.swiggy.com/dapi/restaurants/list/v5?lat=13.008202454086108&lng=77.72806495428085&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING";

// Swiggy API to get Restaurant Menu data with foodfire server
export const swiggy_menu_api_URL ="https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=13.008202454086108&lng=77.72806495428085&restaurantId="
// shimmer card unit
export const shimmer_card_unit = 20;

// shimmer Menu card unit
export const shimmer_menu_card_unit = 4;

// Github - username
export const Github_UserName = "Haritha";
export const Github_Repository_Name = "Namaste-React";

// Github API for User
// export const Github_API_User = "https://api.github.com/users/";

// Social Media Links
// export const Linkedin_Link = "https://www.linkedin.com/in/chetannada/";
// export const Twitter_Link = "https://twitter.com/ChetanNada";
// export const Github_Link = "https://github.com/chetannada";
// export const Email_Link = "mailto:call2chetannada@gmail.com";

// Github Authorization Token
export const options = {
  method: "GET",
  headers: {
    Authorization: "",
  },
};

// menu items api card type key
export const MENU_ITEM_TYPE_KEY =
  "type.googleapis.com/swiggy.presentation.food.v2.ItemCategory";
export const RESTAURANT_TYPE_KEY =
  "type.googleapis.com/swiggy.presentation.food.v2.Restaurant";
// export const IMG_CDN_URL =
//   "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

// export const FETCH_MENU_URL =
//   "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=12.9351929&lng=77.62448069999999&restaurantId=";
// export const restaurantList = [
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "658382",
//       name: "Aruna kitchens",
//       uuid: "8a84644e-7b57-46cb-9775-af648ba93f2e",
//       city: "1",
//       area: "Battarahalli",
//       totalRatingsString: "Too Few Ratings",
//       cloudinaryImageId: "b864a70c509ac70c3107deda2aebba85",
//       cuisines: ["South Indian"],
//       tags: [],
//       costForTwo: 30000,
//       costForTwoString: "₹300 FOR TWO",
//       deliveryTime: 30,
//       minDeliveryTime: 30,
//       maxDeliveryTime: 30,
//       slaString: "30 MINS",
//       lastMileTravel: 2.200000047683716,
//       slugs: {
//         restaurant: "aruna-kitchens-battarahalli-battarahalli",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address:
//         "XPX8+9VM, Ayyappa Nagar, Krishnarajapura, Bengaluru, Karnataka 560036, India",
//       locality: "Ayyappa Nagar",
//       parentId: 395482,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3000,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3000,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3000",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5696881~p=1~eid=00000185-a4c2-6fd5-2a90-cf8c00640165",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "2.2 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "658382",
//         deliveryTime: 30,
//         minDeliveryTime: 30,
//         maxDeliveryTime: 30,
//         lastMileTravel: 2.200000047683716,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "--",
//       totalRatings: 0,
//       new: true,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "221738",
//       name: "Meghana Foods",
//       uuid: "106f4556-6804-4554-8c68-ee875d6acf65",
//       city: "1",
//       area: "Brookefield",
//       totalRatingsString: "5000+ ratings",
//       cloudinaryImageId: "aqsnrylokzpn45qhg1pb",
//       cuisines: [
//         "Biryani",
//         "Andhra",
//         "South Indian",
//         "North Indian",
//         "Chinese",
//         "Seafood",
//       ],
//       tags: [],
//       costForTwo: 50000,
//       costForTwoString: "₹500 FOR TWO",
//       deliveryTime: 35,
//       minDeliveryTime: 35,
//       maxDeliveryTime: 35,
//       slaString: "35 MINS",
//       lastMileTravel: 7.099999904632568,
//       slugs: {
//         restaurant: "meghana-foods-mahadevpura-mahadevpura",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address: "Raj Pinnacle, Mahadevapura, Bengaluru, Karnataka, India",
//       locality: "Mahadevpura",
//       parentId: 635,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 6200,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 6200,
//         message: "",
//         title: "Delivery Charge",
//         amount: "6200",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "7 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "221738",
//         deliveryTime: 35,
//         minDeliveryTime: 35,
//         maxDeliveryTime: 35,
//         lastMileTravel: 7.099999904632568,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.3",
//       totalRatings: 5000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "210119",
//       name: "Sri Jayadurga Biryani",
//       uuid: "13927ae4-7437-4d24-959e-888585c704e8",
//       city: "1",
//       area: "Marathahalli",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "e5k8viofbtrxxo75lxdy",
//       cuisines: ["Biryani", "South Indian", "Andhra", "Hyderabadi", "Snacks"],
//       tags: [],
//       costForTwo: 30000,
//       costForTwoString: "₹300 FOR TWO",
//       deliveryTime: 39,
//       minDeliveryTime: 39,
//       maxDeliveryTime: 39,
//       slaString: "39 MINS",
//       lastMileTravel: 9.699999809265137,
//       slugs: {
//         restaurant: "sri-jayadurga-biryani-marathahalli-marathahalli",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address:
//         "Sri Jaya Durga Restaurant, OPP AMRUTHA BAKERY, LAKSHMI NARAYANA TEMPLE ROAD, MUNNEKOLALA, MARATHAHALLI, BANGALORE",
//       locality: "Munnekollal",
//       parentId: 14529,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 7800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 7800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "7800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 1,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "9.6 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "210119",
//         deliveryTime: 39,
//         minDeliveryTime: 39,
//         maxDeliveryTime: 39,
//         lastMileTravel: 9.699999809265137,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "IT_IS_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "3.6",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "3954",
//       name: "Rajdhani",
//       uuid: "93f169c2-0ac8-4e1d-a46c-41767d247d04",
//       city: "1",
//       area: "Whitefield",
//       totalRatingsString: "100+ ratings",
//       cloudinaryImageId: "h35nhb3lunlpwkyg0euz",
//       cuisines: ["Gujarati", "Rajasthani", "North Indian"],
//       tags: [],
//       costForTwo: 40000,
//       costForTwoString: "₹400 FOR TWO",
//       deliveryTime: 38,
//       minDeliveryTime: 38,
//       maxDeliveryTime: 38,
//       slaString: "38 MINS",
//       lastMileTravel: 5,
//       slugs: {
//         restaurant: "rajdhani-phoenix-mall-whitefield",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address:
//         "Level - 2, Phoenix MarketCity, Mahadevapura, Whitefield Main Road, Bengaluru - 560048",
//       locality: "Phoenix MarketCity",
//       parentId: 753,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 5400,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 5400,
//         message: "",
//         title: "Delivery Charge",
//         amount: "5400",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5666132~p=4~eid=00000185-a4c2-6fd5-2a90-cf8d0064040c",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "3954",
//         deliveryTime: 38,
//         minDeliveryTime: 38,
//         maxDeliveryTime: 38,
//         lastMileTravel: 5,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "3.7",
//       totalRatings: 100,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "8530",
//       name: "Kritunga Restaurant",
//       uuid: "84e612db-d9d4-483d-ad77-81ea42c2208f",
//       city: "1",
//       area: "Marathahalli",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "vxxpqtjryjhhrpoxt65h",
//       cuisines: ["Andhra", "Biryani", "South Indian", "Hyderabadi"],
//       tags: [],
//       costForTwo: 50000,
//       costForTwoString: "₹500 FOR TWO",
//       deliveryTime: 37,
//       minDeliveryTime: 37,
//       maxDeliveryTime: 37,
//       slaString: "37 MINS",
//       lastMileTravel: 9.100000381469727,
//       slugs: {
//         restaurant: "kritunga-kundanhalli-gate-marathahalli",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address:
//         "42 2  Sriven square  Munekollela  Beside star bazaar  Kundanahalli gate  Bangalore",
//       locality: "Kundalahalli",
//       parentId: 20088,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 7800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 7800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "7800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 1,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "9.1 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "8530",
//         deliveryTime: 37,
//         minDeliveryTime: 37,
//         maxDeliveryTime: 37,
//         lastMileTravel: 9.100000381469727,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "IT_IS_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "3.7",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "246128",
//       name: "Hotel Empire",
//       uuid: "e2f6602d-6105-47ed-8de5-cf28d0495851",
//       city: "1",
//       area: "Mahadevpura",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "visisdwdnhzflxgsjpvl",
//       cuisines: ["North Indian", "Kebabs", "Biryani"],
//       tags: [],
//       costForTwo: 25000,
//       costForTwoString: "₹250 FOR TWO",
//       deliveryTime: 35,
//       minDeliveryTime: 35,
//       maxDeliveryTime: 35,
//       slaString: "35 MINS",
//       lastMileTravel: 5,
//       slugs: {
//         restaurant: "empire-mahadevpura-mahadevpura",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address:
//         "Trifecta Adatto, 21, ITPL Main Rd, Garudachar Palya, Mahadevapura, Bengaluru, Karnataka 560048, India",
//       locality: "Garudachar Palya",
//       parentId: 475,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 4600,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 4600,
//         message: "",
//         title: "Delivery Charge",
//         amount: "4600",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "246128",
//         deliveryTime: 35,
//         minDeliveryTime: 35,
//         maxDeliveryTime: 35,
//         lastMileTravel: 5,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.0",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "515426",
//       name: "NAIDU HOTEL",
//       uuid: "2a683c56-86ad-4412-a995-7e6f58b2f8ac",
//       city: "1",
//       area: "Battarahalli",
//       totalRatingsString: "50+ ratings",
//       cloudinaryImageId: "pirep4gspg2izcidygvs",
//       cuisines: ["South Indian", "Chinese", "Snacks"],
//       tags: [],
//       costForTwo: 10000,
//       costForTwoString: "₹100 FOR TWO",
//       deliveryTime: 33,
//       minDeliveryTime: 33,
//       maxDeliveryTime: 33,
//       slaString: "33 MINS",
//       lastMileTravel: 5.800000190734863,
//       slugs: {
//         restaurant: "naidu-hotel-mahadevpura-mahadevpura",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address:
//         "No. 113, tc palaya main road, anandpura, opposite of city kitchen, near brindhavan bar, Bangalore- 560036",
//       locality: "Thambu Chetty Palya Main Road",
//       parentId: 143272,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 4600,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 4600,
//         message: "",
//         title: "Delivery Charge",
//         amount: "4600",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5585778~p=7~eid=00000185-a4c2-6fd5-2a90-cf8e00640770",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "5.8 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "515426",
//         deliveryTime: 33,
//         minDeliveryTime: 33,
//         maxDeliveryTime: 33,
//         lastMileTravel: 5.800000190734863,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.3",
//       totalRatings: 50,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "65769",
//       name: "Burger King",
//       uuid: "c2d3afba-d787-4526-8fd6-8f72b35a5051",
//       city: "1",
//       area: "Whitefield",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "e64zxjsxfycc7azhs0wd",
//       cuisines: ["Burgers", "American"],
//       tags: [],
//       costForTwo: 35000,
//       costForTwoString: "₹350 FOR TWO",
//       deliveryTime: 29,
//       minDeliveryTime: 29,
//       maxDeliveryTime: 29,
//       slaString: "29 MINS",
//       lastMileTravel: 5,
//       slugs: {
//         restaurant: "burger-king-ascends-park-square-itpl-whitefield",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address:
//         "Unit.no. G-9 &G-10,Ground Floor, Ascends Park Square, ITPL, Whitefield Road, Bangalore,-560066",
//       locality: "ITPL Main Road",
//       parentId: 166,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "Get every item under 129",
//         shortDescriptionList: [
//           {
//             meta: "Get every item under 129",
//             discountType: "FinalPrice",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "Get every item under 129",
//             discountType: "FinalPrice",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "",
//         shortDescriptionList: [
//           {
//             meta: "",
//             discountType: "FinalPrice",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "Get every item under 129",
//             discountType: "FinalPrice",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 5400,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 5400,
//         message: "",
//         title: "Delivery Charge",
//         amount: "5400",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "65769",
//         deliveryTime: 29,
//         minDeliveryTime: 29,
//         maxDeliveryTime: 29,
//         lastMileTravel: 5,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.2",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "240552",
//       name: "Udupi Gardenia (jayanthinagar)",
//       uuid: "45f8080f-6a71-4a78-94b1-79768e2a5cfa",
//       city: "1",
//       area: "Ramamurthy nagar",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "lfrcp0wsmohpowae3k26",
//       cuisines: [
//         "South Indian",
//         "North Indian",
//         "Chinese",
//         "Juices",
//         "Ice Cream",
//         "Chaat",
//       ],
//       tags: [],
//       costForTwo: 25000,
//       costForTwoString: "₹250 FOR TWO",
//       deliveryTime: 35,
//       minDeliveryTime: 35,
//       maxDeliveryTime: 35,
//       slaString: "35 MINS",
//       lastMileTravel: 8.800000190734863,
//       slugs: {
//         restaurant: "udupi-gardenia-ramamurthy-nagar-ramamurthy-nagar",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address: "No 135, Horamavu village, Jayanthinagara, Horamavu, 560043",
//       locality: "Jayanthi Nagar",
//       parentId: 20144,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 7000,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 7000,
//         message: "",
//         title: "Delivery Charge",
//         amount: "7000",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 1,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "8.8 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "240552",
//         deliveryTime: 35,
//         minDeliveryTime: 35,
//         maxDeliveryTime: 35,
//         lastMileTravel: 8.800000190734863,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "IT_IS_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.1",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "601058",
//       name: "Dobaraa",
//       uuid: "94a0913a-c99c-4634-b997-4020fc5709c6",
//       city: "1",
//       area: "Mahadevpura",
//       totalRatingsString: "50+ ratings",
//       cloudinaryImageId: "kkisrtk1lphfutyzjv97",
//       cuisines: ["American", "Italian", "Turkish"],
//       tags: [],
//       costForTwo: 80000,
//       costForTwoString: "₹800 FOR TWO",
//       deliveryTime: 43,
//       minDeliveryTime: 43,
//       maxDeliveryTime: 43,
//       slaString: "43 MINS",
//       lastMileTravel: 5,
//       slugs: {
//         restaurant: "dobaraa-mahadevpura-mahadevpura",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address:
//         "2nd Floor - Phoenix Marketcity, Whitefield Main Road, Whitefield, Bangalore, 560048",
//       locality: "Phoenix Market City",
//       parentId: 353018,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 4600,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 4600,
//         message: "",
//         title: "Delivery Charge",
//         amount: "4600",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5690815~p=10~eid=00000185-a4c2-6fd5-2a90-cf8f00640a50",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "601058",
//         deliveryTime: 43,
//         minDeliveryTime: 43,
//         maxDeliveryTime: 43,
//         lastMileTravel: 5,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "3.9",
//       totalRatings: 50,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "424658",
//       name: "Asha Tiffins",
//       uuid: "d79cd5d9-7158-45f1-a198-e563f0e46406",
//       city: "1",
//       area: "Aecs Layout",
//       totalRatingsString: "5000+ ratings",
//       cloudinaryImageId: "hpncnz3sfv3gigsukkts",
//       cuisines: ["South Indian"],
//       tags: [],
//       costForTwo: 20000,
//       costForTwoString: "₹200 FOR TWO",
//       deliveryTime: 33,
//       minDeliveryTime: 33,
//       maxDeliveryTime: 33,
//       slaString: "33 MINS",
//       lastMileTravel: 7.599999904632568,
//       slugs: {
//         restaurant: "asha-tiffins-marathahalli-marathahalli",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address:
//         "#551,AECS Layout main road, 'B' Block AECS Layout,Opp.BBMP ward office,Marathahalli,Bangalore - 560037",
//       locality: "B Block",
//       parentId: 236243,
//       unserviceable: false,
//       veg: true,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 6200,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 6200,
//         message: "",
//         title: "Delivery Charge",
//         amount: "6200",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "7.5 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "424658",
//         deliveryTime: 33,
//         minDeliveryTime: 33,
//         maxDeliveryTime: 33,
//         lastMileTravel: 7.599999904632568,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.4",
//       totalRatings: 5000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "420659",
//       name: "Sri Lakshmi Biryani",
//       uuid: "eb227257-1596-441a-9c84-8265417d2d19",
//       city: "1",
//       area: "Marathahalli",
//       totalRatingsString: "1000+ ratings",
//       cloudinaryImageId: "n7pn6ilfponvcatp0n73",
//       cuisines: ["Biryani", "North Indian", "Snacks"],
//       tags: [],
//       costForTwo: 20000,
//       costForTwoString: "₹200 FOR TWO",
//       deliveryTime: 40,
//       minDeliveryTime: 40,
//       maxDeliveryTime: 40,
//       slaString: "40 MINS",
//       lastMileTravel: 9.699999809265137,
//       slugs: {
//         restaurant: "sri-lakshmi-biryani-kadubeesanahalli-kadubeesanahalli",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address:
//         "No 15&16 Srinivasa Reddy building, Lakshmi Narayana temple road, manunatha layout, munnekoll Bangalore 560037",
//       locality: "Manunatha Layout",
//       parentId: 193940,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 7800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 7800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "7800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 1,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "9.6 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "420659",
//         deliveryTime: 40,
//         minDeliveryTime: 40,
//         maxDeliveryTime: 40,
//         lastMileTravel: 9.699999809265137,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "IT_IS_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "3.6",
//       totalRatings: 1000,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "626214",
//       name: "Bakeshop by Living Food",
//       uuid: "8f9d1db7-35e6-4b93-b082-37cbac9bb20c",
//       city: "1",
//       area: "Mahadevpura",
//       totalRatingsString: "Too Few Ratings",
//       cloudinaryImageId: "b1b712029bce035c45b54ff8ad156a35",
//       cuisines: ["Bakery"],
//       tags: [],
//       costForTwo: 30000,
//       costForTwoString: "₹300 FOR TWO",
//       deliveryTime: 40,
//       minDeliveryTime: 40,
//       maxDeliveryTime: 40,
//       slaString: "40 MINS",
//       lastMileTravel: 4.800000190734863,
//       slugs: {
//         restaurant: "bakeshop-by-living-food-mahadevpura-mahadevpura",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address: "Garudada",
//       locality: "Garudachar Palya",
//       parentId: 374168,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 3800,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 3800,
//         message: "",
//         title: "Delivery Charge",
//         amount: "3800",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5695973~p=13~eid=00000185-a4c2-6fd5-2a90-cf9000640d03",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "4.8 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "626214",
//         deliveryTime: 40,
//         minDeliveryTime: 40,
//         maxDeliveryTime: 40,
//         lastMileTravel: 4.800000190734863,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "--",
//       totalRatings: 0,
//       new: true,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "424612",
//       name: "chickpet donne biriyani house",
//       uuid: "fcd3be65-a939-4c03-948d-55b053065105",
//       city: "1",
//       area: "Whitefield",
//       totalRatingsString: "500+ ratings",
//       cloudinaryImageId: "cem49mnxzx7b0vjmuxe0",
//       cuisines: ["Biryani", "Chinese", "North Indian", "South Indian"],
//       tags: [],
//       costForTwo: 18000,
//       costForTwoString: "₹180 FOR TWO",
//       deliveryTime: 39,
//       minDeliveryTime: 39,
//       maxDeliveryTime: 39,
//       slaString: "39 MINS",
//       lastMileTravel: 9,
//       slugs: {
//         restaurant: "chickpet-donne-biriyani-house-whitefield-whitefield",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address:
//         "Chickpet donne biriyani house Shop No.1, mr complex, opp HP petrol bunk Immadihalli, nagondahalli, main road, Whitefield, Karnataka 560066",
//       locality: "nagondahalli",
//       parentId: 243696,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 7000,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 7000,
//         message: "",
//         title: "Delivery Charge",
//         amount: "7000",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 1,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "9 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "424612",
//         deliveryTime: 39,
//         minDeliveryTime: 39,
//         maxDeliveryTime: 39,
//         lastMileTravel: 9,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "IT_IS_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: false,
//       avgRating: "4.1",
//       totalRatings: 500,
//       new: false,
//     },
//     subtype: "basic",
//   },
//   {
//     type: "restaurant",
//     data: {
//       type: "F",
//       id: "153606",
//       name: "Goodness To Go",
//       uuid: "1a0036cf-f04c-418c-b7d7-0f7af6ef8e31",
//       city: "1",
//       area: "Whitefield",
//       totalRatingsString: "500+ ratings",
//       cloudinaryImageId: "s3s3atlgvfaiczt8syn0",
//       cuisines: [
//         "European",
//         "Italian",
//         "American",
//         "Pastas",
//         "Salads",
//         "Juices",
//         "Desserts",
//         "Combo",
//       ],
//       tags: [],
//       costForTwo: 35000,
//       costForTwoString: "₹350 FOR TWO",
//       deliveryTime: 39,
//       minDeliveryTime: 39,
//       maxDeliveryTime: 39,
//       slaString: "39 MINS",
//       lastMileTravel: 4.300000190734863,
//       slugs: {
//         restaurant:
//           "goodness-to-go-by-smoke-house-deli-forum-shantiniketan-whitefield",
//         city: "bangalore",
//       },
//       cityState: "1",
//       address:
//         "Smoke House Deli, 012, Lower Ground Floor, Forum Shantiniketan Mall, Whitefield, Bengaluru, Karnataka 560067",
//       locality: "Forum Shantiniketan Mall",
//       parentId: 12021,
//       unserviceable: false,
//       veg: false,
//       select: false,
//       favorite: false,
//       tradeCampaignHeaders: [],
//       aggregatedDiscountInfo: {
//         header: "60% off",
//         shortDescriptionList: [
//           {
//             meta: "60% off | Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       aggregatedDiscountInfoV2: {
//         header: "60% OFF",
//         shortDescriptionList: [
//           {
//             meta: "Use WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         descriptionList: [
//           {
//             meta: "60% off up to ₹100 | Use code WELCOMEBACK",
//             discountType: "Percentage",
//             operationType: "RESTAURANT",
//           },
//         ],
//         subHeader: "",
//         headerType: 0,
//         superFreedel: "",
//       },
//       ribbon: [
//         {
//           type: "PROMOTED",
//         },
//       ],
//       chain: [],
//       feeDetails: {
//         fees: [
//           {
//             name: "distance",
//             fee: 4600,
//             message: "",
//           },
//           {
//             name: "time",
//             fee: 0,
//             message: "",
//           },
//           {
//             name: "special",
//             fee: 0,
//             message: "",
//           },
//         ],
//         totalFees: 4600,
//         message: "",
//         title: "Delivery Charge",
//         amount: "4600",
//         icon: "",
//       },
//       availability: {
//         opened: true,
//         nextOpenMessage: "",
//         nextCloseMessage: "",
//       },
//       longDistanceEnabled: 0,
//       rainMode: "NONE",
//       thirdPartyAddress: false,
//       thirdPartyVendor: "",
//       adTrackingID: "cid=5698774~p=16~eid=00000185-a4c2-6fd5-2a90-cf9100641006",
//       badges: {
//         imageBased: [],
//         textBased: [],
//         textExtendedBadges: [],
//       },
//       lastMileTravelString: "4.3 kms",
//       hasSurge: false,
//       sla: {
//         restaurantId: "153606",
//         deliveryTime: 39,
//         minDeliveryTime: 39,
//         maxDeliveryTime: 39,
//         lastMileTravel: 4.300000190734863,
//         lastMileDistance: 0,
//         serviceability: "SERVICEABLE",
//         rainMode: "NONE",
//         longDistance: "NOT_LONG_DISTANCE",
//         preferentialService: false,
//         iconType: "EMPTY",
//       },
//       promoted: true,
//       avgRating: "4.3",
//       totalRatings: 500,
//       new: false,
//     },
//     subtype: "basic",
//   },
// ];
